# fly.toml app configuration file generated for node-docker on 2023-07-18T12:42:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-docker"
primary_region = "jnb"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
[redis_service]
  internal_port = 6379
  protocol ="tcp"
[]
